// This file is generated by Velite

import type __vc from '../velite.config.mts'

type Collections = typeof __vc.collections

export type Index = Collections['index']['schema']['_output']
export declare const index: Index

export type Doc = Collections['docs']['schema']['_output']
export declare const docs: Doc[]
